#!/usr/bin/env python3
"""Build a 7-DOF rail-mounted PiPER URDF from the verified arm model."""

from __future__ import annotations

import copy
import xml.etree.ElementTree as ET
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
SOURCE = PROJECT_DIR / "robots" / "piper" / "piper_arm.urdf"
OUTPUT = PROJECT_DIR / "robots" / "piper_rail" / "piper_rail.urdf"
RAIL_ORIGIN = (0.33, 1.55, 0.92)
# Fixed calibration between the existing PiPER URDF FK and the MuJoCo model.
# This makes q=0 gripper_center coincide in the two independent simulators.
ARM_MOUNT_ORIGIN = (-0.00117525, -0.00000082, -0.02012027)
ARM_MOUNT_RPY = (3.141592653589793, 0.0, 0.0)


def main() -> None:
    source_root = ET.parse(SOURCE).getroot()
    root = ET.Element("robot", name="piper_v100_rail")
    root.append(ET.Element("link", name="world_base"))

    carriage = ET.Element("link", name="rail_carriage")
    collision = ET.SubElement(carriage, "collision")
    geometry = ET.SubElement(collision, "geometry")
    ET.SubElement(geometry, "box", size="0.20 0.24 0.06")
    root.append(carriage)

    rail_joint = ET.Element("joint", name="rail_slide", type="prismatic")
    ET.SubElement(rail_joint, "parent", link="world_base")
    ET.SubElement(rail_joint, "child", link="rail_carriage")
    ET.SubElement(
        rail_joint,
        "origin",
        xyz=" ".join(str(value) for value in RAIL_ORIGIN),
        rpy="0 0 0",
    )
    ET.SubElement(rail_joint, "axis", xyz="1 0 0")
    ET.SubElement(
        rail_joint,
        "limit",
        lower="-0.40",
        upper="0.40",
        effort="500",
        velocity="0.50",
    )
    root.append(rail_joint)

    for link in source_root.findall("link"):
        root.append(copy.deepcopy(link))

    mount = ET.Element("joint", name="rail_carriage_to_arm_base", type="fixed")
    ET.SubElement(mount, "parent", link="rail_carriage")
    ET.SubElement(mount, "child", link="arm_base")
    ET.SubElement(
        mount,
        "origin",
        xyz=" ".join(str(value) for value in ARM_MOUNT_ORIGIN),
        rpy=" ".join(str(value) for value in ARM_MOUNT_RPY),
    )
    root.append(mount)

    for joint in source_root.findall("joint"):
        root.append(copy.deepcopy(joint))

    ET.indent(root, space="  ")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        '<?xml version="1.0"?>\n'
        '<!-- Generated by scripts/build_rail_piper_urdf.py; do not edit manually. -->\n'
        + ET.tostring(root, encoding="unicode")
        + "\n",
        encoding="utf-8",
    )
    print(OUTPUT)


if __name__ == "__main__":
    main()
