#!/usr/bin/env python3
"""Build a fixed-base, 12-DOF dual-PiPER URDF from the single-arm model."""

from __future__ import annotations

import copy
import xml.etree.ElementTree as ET
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
SOURCE = PROJECT_DIR / "robots" / "piper" / "piper_arm.urdf"
OUTPUT = PROJECT_DIR / "robots" / "piper" / "piper_dual_arm.urdf"
PARTNER_BASE_X = 0.66


def prefixed(element: ET.Element, prefix: str) -> ET.Element:
    result = copy.deepcopy(element)
    if "name" in result.attrib:
        result.attrib["name"] = prefix + result.attrib["name"]
    for tag in ("parent", "child"):
        child = result.find(tag)
        if child is not None:
            child.attrib["link"] = prefix + child.attrib["link"]
    mimic = result.find("mimic")
    if mimic is not None:
        mimic.attrib["joint"] = prefix + mimic.attrib["joint"]
    return result


def fixed_base_joint(prefix: str, xyz: str, yaw: float) -> ET.Element:
    joint = ET.Element("joint", name=f"world_to_{prefix}arm_base", type="fixed")
    ET.SubElement(joint, "parent", link="world_base")
    ET.SubElement(joint, "child", link=f"{prefix}arm_base")
    ET.SubElement(joint, "origin", xyz=xyz, rpy=f"0 0 {yaw:.16g}")
    return joint


def main() -> None:
    source_root = ET.parse(SOURCE).getroot()
    output_root = ET.Element("robot", name="dual_piper_v100")
    output_root.append(ET.Element("link", name="world_base"))

    links = source_root.findall("link")
    joints = source_root.findall("joint")
    for prefix, xyz, yaw in (
        ("primary_", "0 0 0", 0.0),
        ("partner_", f"{PARTNER_BASE_X} 0 0", 3.141592653589793),
    ):
        for link in links:
            output_root.append(prefixed(link, prefix))
        output_root.append(fixed_base_joint(prefix, xyz, yaw))
        for joint in joints:
            output_root.append(prefixed(joint, prefix))

    ET.indent(output_root, space="  ")
    OUTPUT.write_text(
        '<?xml version="1.0"?>\n'
        '<!-- Generated by scripts/build_dual_piper_urdf.py; do not edit manually. -->\n'
        + ET.tostring(output_root, encoding="unicode")
        + "\n",
        encoding="utf-8",
    )
    print(OUTPUT)


if __name__ == "__main__":
    main()
